### ISSUE TITLE
Faraday problem

### ISSUE THREAD

**Issue by dolarsrg** [gocardless/gocardless-pro-ruby#29]
Using gocardless_pro (2.1.0) and faraday (0.8.11) with faraday_middleware (0.8.8) I got this error:

```ruby
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/santi/.rvm/gems/ruby-2.4.1/gems/faraday-0.8.11/lib/faraday/connection.rb:39:in `initialize'
	from /Users/santi/.rvm/gems/ruby-2.4.1/gems/faraday-0.8.11/lib/faraday.rb:11:in `new'
	from /Users/santi/.rvm/gems/ruby-2.4.1/gems/faraday-0.8.11/lib/faraday.rb:11:in `new'
	from /Users/santi/.rvm/gems/ruby-2.4.1/gems/gocardless_pro-2.1.0/lib/gocardless_pro/api_service.rb:25:in `initialize'
	from /Users/santi/.rvm/gems/ruby-2.4.1/gems/gocardless_pro-2.1.0/lib/gocardless_pro/client.rb:86:in `new'
	from /Users/santi/.rvm/gems/ruby-2.4.1/gems/gocardless_pro-2.1.0/lib/gocardless_pro/client.rb:86:in `initialize'
```

Every time I try to run:
```ruby
GoCardlessPro::Client.new(
      access_token: self.gc_access_token,
      environment: :sandbox
    )
```

Everything works great with faraday (0.9.2), but gocardless_pro (2.1.0) requires faraday (>= 0.8.9, < 0.10). You might should require a greater version.

**Comment by nickcampbell18** [comment]
Thanks for the report! This looks like a fairly rubbish experience - will take a look.

**Comment by nickcampbell18** [comment]
OK, there are two reasonable paths here:

1. Increase the minimum Faraday version to 0.9.2, where the client initialization takes `nil` as a second argument rather than a hash: https://github.com/lostisland/faraday/compare/v0.8.11...v0.9.2#diff-ec23de93634c9f1330648fecdfd152dfR57

2. Make this code more clever with older Faradays.

I think the former is preferable, so I will submit a fix shortly.
