### ISSUE TITLE
Updating refunds

### ISSUE THREAD

**Issue by ShadowKoBolt** [gocardless/gocardless-pro-ruby#40]
When updating a refund (e.g. `@client.refunds.update("RF00001YZK196Y", params: { metadata: { foo: "bar" } })` you are currently met with an error `NoMethodError: undefined method `[]' for nil:NilClass`

This is because the update response is in the format 
```
=> {"payment_refunds"=>
  {"id"=>"RFXXX",
   "amount"=>4370,
   "created_at"=>"2018-11-23T13:17:39.523Z",
   "reference"=>"Service refund",
   "metadata"=>{"foo"=>"bar"},
   "currency"=>"GBP",
   "links"=>{"payment"=>"xxx", "mandate"=>"xxx"}}}
```

Which uses a would require a different envelope key in the refunds_service (currently it uses `refunds`)

**Comment by nickcampbell18** [comment]
Hi @ShadowKoBolt, we've fixed the API (it was incorrectly returning `"payment_refunds"` as the top-level key, rather than just `"refunds"`).

Fortunately, you look to have been the only person affected by this change, so we didn't consider it breaking. Please let us know if you have any further problems!
